name: Peer Cipriani
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3988
title: Kiteboarding Athlete
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#c1c1c1'
    - '#6f6f6f'
    - '#3d3d3d'
    - '#181818'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
