name: Peer Cipriani
favicon: null
layout_spectrum: 0.9582752427086234
typography_spectrum: 0.6240583974868059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.956441747257486
  lightness: 0.7156020095571876
  saturation: 0.3766289211343974
  rhythmicContrast: 0.609163528541103
purpose: []
